name: spellcheck 
on:
  workflow_call:
    secrets:
      RESUSABLE_GH_ACTION_TOKEN:
        required: true
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
     - name: spellcheck checkout
       uses: actions/checkout@v2
     - name: download spellcheck config file
       run: |
        wget https://raw.githubusercontent.com/devonfw/.github/master/.github/workflows/.spellcheck.yml -O ./.spellcheck.yml
     - uses: igsekor/pyspelling-any@v0.0.2
       name: Spellcheck
